const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST"
const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE"
const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS"
const LOADING_TRUE = "LOADING_TRUE"
const LOADING_FALSE = "LOADING_FALSE"

export { FETCH_JOBS_REQUEST, FETCH_JOBS_FAILURE, FETCH_JOBS_SUCCESS, LOADING_TRUE, LOADING_FALSE }