const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST"
const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE"
const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS"

export { FETCH_JOBS_REQUEST, FETCH_JOBS_FAILURE, FETCH_JOBS_SUCCESS }